version: "3.4"

services:
  react-1:
    image: react
    ports:
      - 3001:5000
  react-2:
    image: react
    ports:
      - 3002:5000
  loadbalancer:
    build: ./load-balancer
    tty: true
    links:
      - react-1
      - react-2
    ports:
      - "8080:8080"
